from tests.helpers import create_test_merchant
import uuid
import pytest
from app.models.audit_event import AuditEvent

def test_e2e_optimization_loop(client, db_session):
    # 1. Register Merchant A
    unique_email_a = f"merchant_e2e_a_{uuid.uuid4().hex[:8]}@example.com"
    reg_a = create_test_merchant(db_session, unique_email_a, "Password123!")
    assert reg_a.status_code == 201
    token_a = reg_a.json()["access_token"]
    headers_a = {"Authorization": f"Bearer {token_a}"}
    merch_a_id = client.get("/api/v1/merchants/me", headers=headers_a).json()["id"]

    # 2. Register Merchant B (for cross-merchant test)
    unique_email_b = f"merchant_e2e_b_{uuid.uuid4().hex[:8]}@example.com"
    reg_b = create_test_merchant(db_session, unique_email_b, "Password123!")
    token_b = reg_b.json()["access_token"]
    headers_b = {"Authorization": f"Bearer {token_b}"}

    # 3. Create a product for Merchant A that lacks delivery_days to trigger a DELIVERY_UNKNOWN friction
    p_res = client.post(
        "/api/v1/products",
        json={
            "name": "E2E Test Product",
            "description": "A product for e2e testing lacking delivery info",
            "category": "electronics",
            "price": 100000, # 1000 INR
            "currency": "INR",
            "metadata": {"return_days": 15} # delivery_days is intentionally missing
        },
        headers=headers_a
    )
    assert p_res.status_code == 201
    prod_id = p_res.json()["id"]

    # 4. Run Initial Simulation (Test A: Real simulation)
    sim1_res = client.post(
        "/api/v1/optimization/simulations",
        json={
            "merchant_id": merch_a_id,
            "scenario_count": 5,
            "buyer_profiles": ["SPEED"] # Guarantee delivery-constrained personas
        },
        headers=headers_a
    )
    assert sim1_res.status_code == 200
    sim1_data = sim1_res.json()
    assert sim1_data["status"] == "COMPLETED"

    # Assert that at least one generated scenario explicitly requires a delivery deadline
    assert any(res.get("intent", {}).get("delivery_deadline_days") is not None for res in sim1_data["results"]), "Expected at least one scenario to require a delivery deadline"

    # Store initial friction count to compare later (Test H)
    frictions_sim1 = [
        f for res in sim1_data["results"] for f in res.get("frictions", [])
        if f["product_id"] == prod_id and f["reason"] == "DELIVERY_UNKNOWN"
    ]
    assert len(frictions_sim1) > 0, "Expected simulation to detect missing delivery_days friction"

    # 5. Fetch Recommendations
    recs_res = client.get("/api/v1/optimization/recommendations", headers=headers_a)
    assert recs_res.status_code == 200
    recs = recs_res.json()

    # Find the recommendation generated by the simulation
    delivery_recs = [r for r in recs if r["type"] == "DELIVERY_UNKNOWN" and prod_id in r.get("action_data", {}).get("affected_product_ids", [])]
    assert len(delivery_recs) > 0, "Simulation did not generate the expected recommendation"
    rec = delivery_recs[0]
    rec_id = rec["id"]

    assert rec["status"] == "PROPOSED"

    # 6. Test J: Cross-merchant access rejection
    patch_b = client.patch(f"/api/v1/optimization/recommendations/{rec_id}/status", json={"status": "APPLIED"}, headers=headers_b)
    assert patch_b.status_code == 404, "Merchant B should not be able to apply Merchant A's recommendation"

    # 7. Test I: What-If safety (does not mutate DB)
    what_if_res = client.post(
        "/api/v1/optimization/what-if",
        json={
            "merchant_id": merch_a_id,
            "hypothesis": "Test what-if safety",
            "modifications": {
                "delivery_days": 2
            }
        },
        headers=headers_a
    )
    assert what_if_res.status_code == 200

    # Verify DB not mutated by What-if
    p_check_whatif = client.get(f"/api/v1/products/{prod_id}", headers=headers_a).json()
    assert p_check_whatif["metadata"].get("delivery_days") is None, "What-If simulation leaked state to DB"

    # 8. Test E & B: Status transitions to APPLIED only on success, and PostgreSQL mutation
    # We apply the recommendation
    patch_a = client.patch(f"/api/v1/optimization/recommendations/{rec_id}/status", json={"status": "APPLIED"}, headers=headers_a)
    assert patch_a.status_code == 200
    assert patch_a.json()["status"] == "APPLIED"

    # Verify PostgreSQL mutation (Test B)
    p_check_applied = client.get(f"/api/v1/products/{prod_id}", headers=headers_a).json()
    assert p_check_applied["metadata"].get("delivery_days") is not None
    assert p_check_applied["metadata"]["delivery_days"] > 0
    new_delivery_days = p_check_applied["metadata"]["delivery_days"]

    # 9. Test C & D: AuditEvent created with Before/After values
    audits = db_session.query(AuditEvent).filter(
        AuditEvent.merchant_id == uuid.UUID(merch_a_id),
        AuditEvent.event_type == "RECOMMENDATION_APPLIED",
        AuditEvent.entity_id == uuid.UUID(prod_id)
    ).all()
    assert len(audits) == 1
    audit = audits[0]

    assert audit.event_data["recommendation_id"] == rec_id
    assert audit.event_data["before_state"].get("delivery_days") is None
    assert audit.event_data["after_state"]["delivery_days"] == new_delivery_days

    # 10. Test F: Idempotency
    patch_idem = client.patch(f"/api/v1/optimization/recommendations/{rec_id}/status", json={"status": "APPLIED"}, headers=headers_a)
    assert patch_idem.status_code == 200

    audits_idem = db_session.query(AuditEvent).filter(
        AuditEvent.merchant_id == uuid.UUID(merch_a_id),
        AuditEvent.event_type == "RECOMMENDATION_APPLIED",
        AuditEvent.entity_id == uuid.UUID(prod_id)
    ).all()
    assert len(audits_idem) == 1, "Idempotent apply should not create duplicate audit events"

    p_check_idem = client.get(f"/api/v1/products/{prod_id}", headers=headers_a).json()
    assert p_check_idem["metadata"]["delivery_days"] == new_delivery_days

    # 11. Test G & H: Ability to rerun the same simulation and simulation observing changed state
    sim2_res = client.post(
        "/api/v1/optimization/simulations",
        json={
            "merchant_id": merch_a_id,
            "scenario_count": 5,
            "buyer_profiles": ["SPEED"]
        },
        headers=headers_a
    )
    assert sim2_res.status_code == 200
    sim2_data = sim2_res.json()

    frictions_sim2 = [
        f for res in sim2_data["results"] for f in res.get("frictions", [])
        if f["product_id"] == prod_id and f["reason"] == "DELIVERY_UNKNOWN"
    ]

    # The friction count should drop because we applied the delivery fix
    assert len(frictions_sim2) == 0, "Expected simulation to observe changed state and drop the friction"

    # Ensure total frictions decreased
    total_frictions_sim1 = sum(len(r.get("frictions", [])) for r in sim1_data["results"])
    total_frictions_sim2 = sum(len(r.get("frictions", [])) for r in sim2_data["results"])
    assert total_frictions_sim2 < total_frictions_sim1, "Expected overall friction count to decrease after recommendation apply"
