"""Add review counts to CatalogueImportJob

Revision ID: 52186f3d289e
Revises: 80d7558b55b4
Create Date: 2026-09-05 15:14:35.744998+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52186f3d289e'
down_revision: Union[str, None] = '80d7558b55b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogue_import_jobs', sa.Column('ready_row_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('catalogue_import_jobs', sa.Column('needs_review_row_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('catalogue_import_jobs', sa.Column('needs_fix_row_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('catalogue_import_jobs', sa.Column('duplicate_row_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('catalogue_import_jobs', sa.Column('excluded_row_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalogue_import_jobs', 'excluded_row_count')
    op.drop_column('catalogue_import_jobs', 'duplicate_row_count')
    op.drop_column('catalogue_import_jobs', 'needs_fix_row_count')
    op.drop_column('catalogue_import_jobs', 'needs_review_row_count')
    op.drop_column('catalogue_import_jobs', 'ready_row_count')
    # ### end Alembic commands ###
