"""add_catalogue_import_jobs

Revision ID: 80d7558b55b4
Revises: 7eccee1c6f27
Create Date: 2026-09-05 14:28:19.592838+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d7558b55b4'
down_revision: Union[str, None] = '7eccee1c6f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogue_import_jobs',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('schema_type', sa.String(length=100), nullable=False),
    sa.Column('ai_mapper_used', sa.Boolean(), nullable=False),
    sa.Column('ai_mapper_provider', sa.String(length=50), nullable=True),
    sa.Column('has_low_confidence_mappings', sa.Boolean(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_row_count', sa.Integer(), nullable=False),
    sa.Column('invalid_row_count', sa.Integer(), nullable=False),
    sa.Column('analysis_payload', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('import_result', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogue_import_jobs_id'), 'catalogue_import_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_catalogue_import_jobs_merchant_id'), 'catalogue_import_jobs', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_catalogue_import_jobs_status'), 'catalogue_import_jobs', ['status'], unique=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'User'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'User'::character varying"))
    op.drop_index(op.f('ix_catalogue_import_jobs_status'), table_name='catalogue_import_jobs')
    op.drop_index(op.f('ix_catalogue_import_jobs_merchant_id'), table_name='catalogue_import_jobs')
    op.drop_index(op.f('ix_catalogue_import_jobs_id'), table_name='catalogue_import_jobs')
    op.drop_table('catalogue_import_jobs')
    # ### end Alembic commands ###
